### ISSUE TITLE
Import the project in latest RHPam

### ISSUE THREAD

**Issue by plorent** [effectivebpmwithjbossbpm/chapter-2-travel-agency-demo#2]
Not an issue but a question. Since this is a very interesting project to learn/study, would it be feasible to import the project(s) into the latest release of RHPam?

**Comment by eschabell** [comment]
> Not an issue but a question. Since this is a very interesting project to learn/study, would it be feasible to import the project(s) into the latest release of RHPam?

Most of this project moved over to gitlab so might be more relevant to explore some of the content found there that is maybe not exatcly this but it's moved up to Red Hat Process Automation Manager:

- Running them on CodeReady Containers, just explore here: https://gitlab.com/redhatdemocentral
- Running locally or in a local developer container, just explore here: https://gitlab.com/bpmworkshop
- Any there are workshops showing you how to do this for RHPAM and RHDM here: https://bpmworkshop.gitlab.io/#/1

Also handy to watch the progress and updates I write about here: https://www.schabell.org/search/label/Process%20Automation%20Manager

Hope this helps?

**Comment by plorent** [comment]
Thanks Eric. Your book is a nice not so simple example and it would have been awesome to see it running in the latest RHPAM. That said, I'll follow the links you have posted. Thank you very much. Peter

**Comment by eschabell** [comment]
> Thanks Eric. Your book is a nice not so simple example and it would have been awesome to see it running in the latest RHPAM. That said, I'll follow the links you have posted. Thank you very much. Peter

Thanks, appreciate the kind words and to fix this would require a rewrite of this book which is not in my planning at the moment. Good luck and reach out anytime if you have troubles with RHPAM and the above provided examples. I'm happy to help anyone learning this!
